version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dist_sys
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - node-network

  # Backend Application Service
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:dist_sys@localhost:27017/db
    depends_on:
      - mongodb
    networks:
      - node-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb-data:

networks:
  node-network:
    driver: bridge